name: XarXiv

on:
  workflow_dispatch:
  schedule:
  #https://jasonet.co/posts/scheduled-actions/
  #       ┌───────────── minute (0 - 59)
  #       │ ┌───────────── hour (0 - 23)
  #       │ │ ┌───────────── day of the month (1 - 31)
  #       │ │ │ ┌───────────── month (1 - 12)
  #       │ │ │ │ ┌───────────── day of the week (0 - 6) Sun-Mon...Sat
  #       │ │ │ │ │
  #       │ │ │ │ │
  #       │ │ │ │ │
  #       * * * * *
  - cron: '0 4 ? * 1,2,3,4,5'
  
jobs:
  build:
  
    runs-on: ubuntu-latest
    steps:

    - name: checkout repo content
      uses: actions/checkout@v4 # checkout the repository content

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' # install the python version needed

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: execute py script # run crosslist.py
      run: python crosslist.py > index.html

    - name: commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add index.html
        git commit -m "new run happened" -a || true

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: main 

    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        git clone https://github.com/ammaraskar/sphinx-action-test.git --branch gh-pages --single-branch gh-pages
        cp -r index.html gh-pages/
        cd gh-pages
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
  # ===============================
